version: "3"
virtualbrowsers:
- name: kibana-virtual
  url: http://kubernetes-vm.${_SANDBOX_ID}.svc.cluster.local:30001/app/dashboard
virtualmachines:
- name: kubernetes-vm
  image: elastic-pme-team/k3s-latest-0b3ea7e6-5284-4fa3-8d1b-50c6f23bffa5
  shell: /bin/bash
  memory: 16384
  cpus: 16
  allow_external_ingress:
  - https
- name: host-vm
  image: ubuntu-os-cloud/ubuntu-2204-lts
  memory: 4096
  cpus: 1
secrets:
- name: GCSKEY_EDEN_WORKSHOP
